---
# Restart server
- name: Stop and remove docker container
  listen: restart service
  docker_container:
    name: api
    image: api
    state: absent
  become: true
- name: Build docker image
  listen: restart service
  become: true
  docker_image:
    # pull: true
    build:
      path: /home/ssps/web/server
      rm: false
    source: build
    name: api
    tag: latest
- name: Start docker container
  listen: restart service
  docker_container:
    name: api
    image: api
    state: started
    published_ports:
      - 3001:3001
    networks:
      - name: mongodb
    env:
      PRIVATE_RSA_KEY: "{{PRIVATE_RSA_KEY}}"
      PUBLIC_RSA_KEY: "{{PUBLIC_RSA_KEY}}"
      MONGODB: "{{MONGODB}}"
      MONGODB_PASSWORD: "{{MONGODB_PASSWORD}}"
  become: true

# Restart client
- name: update dependencies
  listen: restart service
  become: false
  community.general.npm:
    path: /home/ssps/web/client
- name: build the client
  listen: restart service
  become: false
  command:
    cmd: npm run prod
    chdir: /home/ssps/web/client