---
- name: restart server
  tasks:
    - name: Build docker image
      docker_image:
        path: /home/ssps/db
        name: api
        tag: latest
    - name: Start docker container
      docker_container:
        name: api
        image: api
        state: restarted
      become: true
- name: restart client
  tasks:
    - name: update dependencies
      community.general.npm:
        path: /home/ssps/web
    - name: build the client
      command:
        cmd: npx vue-cli-service build
        chdir: /home/ssps/web