---
- name: MongoDB data folder exists
  file:
    path: /home/ssps/mongo-data
    state: directory
## Ansible failed. For first run, uncomment, then recomment this.
# - name: MongoDB server
#   include_role:
#     name: mongodb
#   vars:
#     tags: ['database']
#     mongodb_container_name: 'mongodb'
#     mongodb_port: 27017
#     mongodb_auth: true
#     mongodb_db: databaze
#     mongodb_user: dbuzivatel
#     mongodb_password: "{{ MONGODB_PASSWORD }}"
#     mongodb_docker_image: mongo
#     mongodb_docker_image_tag: 5.0.9
#     mongodb_install_cli: false
#     mongodb_container_memory_limit: 512m
#     mongodb_volumes:
#       - "/home/ssps/mongo-data:/data/db"
- name: create docker network
  docker_network:
    name: mongodb
    ipam_config:
      - subnet: 172.28.0.1/24
- name: Connect mongodb to correct network
  docker_container: 
    name: mongodb
    networks:
      - name: mongodb
        ipv4_address: 172.28.0.2
- name: CLIENT - Download sources
  become: false
  git:
    dest: /home/ssps/web
    repo: ssh://git@github.com/UJEP-ssps/ujep
    depth: 1
  notify: restart service