- name: Ensure db client packages are installed (Debian/Ubuntu)
  apt: name={{item}} state=present
  with_items:
    - mongodb-org-tools
  when: mongodb_install_cli and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')