---
- name: Pull MongoDb image
  docker_image:
    name: '{{ mongodb_docker_image }}'
    tag: '{{ mongodb_docker_image_tag }}'
    source: pull

- name: Run mongodb container
  docker_container:
    name: '{{ mongodb_container_name }}'
    image: '{{ mongodb_docker_image }}:{{ mongodb_docker_image_tag }}'
    # restart_policy: unless-stopped
    state: started
    memory: '{{ container_memory_limit | default(omit) }}'
    env: '{{ mongodb_env | combine(mongodb_auth_env) }}'
    volumes: '{{ mongodb_volumes + [mongodb_users_config_mount] }}'
    ports:
      - '0.0.0.0:{{ mongodb_port }}:{{ mongodb_internal_port }}'
  register: mongodb_container

- name: Wait until mongodb starts up
  wait_for:
    port: '{{ mongodb_port }}'
    delay: 5
