---
- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Nginx config
  become: true
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx