---
- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Add cert key
  become: true
  copy:
    content: {{CERT_KEY}}
    dest: /etc/nginx/fancy

- name: Nginx config
  become: true
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx